name: CONTEXT DUMP LOGS
run-name: Dump all the context in the GHAs
on:
  push:
    branches:
      - context
jobs:
  GITHUB-CTX:
    name: Dump github context itself
    runs-on: ubuntu-latest
    steps:
      - name: Dump GITHUB-CTX
        run: |
          echo "GITHUB context: ${{ toJson(github) }}"
  CHECK-EVENT-NAME:
    name: Check the event name
    runs-on: ubuntu-latest
    if: ${{ github.event_name === 'push' }}
    steps:
      - name: Dump event name if PUSH
        run: |
          echo "The event triggers this WF is push
        
