name: LEARNING GITHUB ACTIONS
run-name: Discover bat version
on: [push]

env:
  DEV_NAME: VinhPham
  DEPT_ID: Dev
jobs:
  Job1-and-1:
    runs-on: ubuntu-latest
    defaults:
      run:
#        shell: bash
        working-directory: ./utils
    steps:
      - name: Check out branch
        uses: actions/checkout@v4
#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
      - name: Check repo status
        run: |
          ls ${{ github.workspace }}
          echo "${{ github.workspace }} is the working space. Check defaults"
          echo "List all file in the workspace"
      - name: Run script inside 'utils' directory
        run: |
          ./greeting.sh
          ./yahoo.sh
      - name: Check Custom Environment
        run: |
          echo "Workflow global scope: $DEV_NAME"
          echo "Workflow local scope: $LOCAL_DEV_NAME"
        env:
          LOCAL_DEV_NAME: vinh.pham
      - name: Dump all default environment variables in job1
        run: env
#      - run: npm install -g bats
#      - run: bats -v

  Job2-in-PARALELL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Check workspace location with scripts
        run: ./greeting.sh
      - name: Check the scripts inside 'utils' directory
        run: ./utils/yahoo.sh
      - name: Run script with variable
        run: |
          echo "${{ github.action }}"
          echo "${{ github.actor }}"
          echo "${{ github.job }}"
          ./utils/yahoo.sh
        env:
          TEST_ENV: apply-2.0-for-test
      - name: Dump env in Job2
        run: env
  Job3-Save-Artifacts:
    name: Save Output
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 9 > artifacts-output.log
      - name: Upload this artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-output-add-operator
          path: artifacts-output.log

  Job4-Download-Artifact:
    name: Download artifact of add operator
    runs-on: ubuntu-latest
    needs: Job3-Save-Artifacts
    steps:
      - name: Download available artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-output.log


