name: LEARNING GITHUB ACTIONS
run-name: Discover bat version
on: [push]

jobs:
  DISCOVERY-BAT-VER:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./utils
    steps:
      - name: Check repo status
        run: |
          ls ${{ github.workspace }}
          echo "${{ github.workspace }} is the working space. Check defaults"
          echo "List all file in the workspace"
      - name: Run script before others
        run: |
          ./utils/greetings.sh
          ./utils/yahoo.sh
      - name: Check out branch
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g bats
      - run: bats -v

  PARALELL-JOB:
    runs-on: ubuntu-latest
    steps:
      - name: Just check the windows runner
        uses: actions/checkout@v4
