name: LEARNING GITHUB ACTIONS
run-name: Discover bat version
on: [push]

jobs:
  Job1-and-1:
    runs-on: ubuntu-latest
    defaults:
      run:
#        shell: bash
        working-directory: ./utils
    steps:
      - name: Check out branch
        uses: actions/checkout@v4
#      - name: Set up Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20'
      - name: Check repo status
        run: |
          ls ${{ github.workspace }}
          echo "${{ github.workspace }} is the working space. Check defaults"
          echo "List all file in the workspace"
      - name: Run script inside 'utils' directory
        run: |
          ./greetings.sh
#          ./yahoo.sh
#      - run: npm install -g bats
#      - run: bats -v

  Job2-in-PARALELL:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Check workspace location with scripts
        run: ./greeting.sh
      - name: Check the scripts inside 'utils' directory
        run: ./utils/yahoo.sh
      - name: Run script with variable
        run: |
          echo "${{ github.action }}"
          echo "${{ github.actor }}"
          echo "${{ github.job }}"
          echo "${{ github.test_env}}"
        env:
          TEST_ENV: apply-2.0-for-test
